


name: Java Maven Build & Publish Artifact

on:
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - run: mvn -B clean package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-jar
          path: target/*.jar

  publish-job:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-jar
          path: staging
      - name: Upload final artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging

